export const ENDPOINTS = {
  register: 'user/register',
  login: 'user/login',
  ChangePass: 'user/change-password',
  Social: 'user/social-login',
  forgotPass: 'user/forgot-password',
  updateProfile: 'user/update-profile',
  AddDog: 'dog/create',
  GetDogList: 'dog/dogs-details',
  DeleteDog: 'dog/delete-dog-detail',
  detailDog: 'dog/dog-detail',
  UpdatelDog: 'dog/dog-details-update',
  buslist: 'booking/route-list',
  CreateBooking: 'booking/new-booking',
  bookinglist: 'booking/booking-list',
  bookdetails: 'booking/dog-booking-detail',
};
